CONFIG = {};

//API STATUS
CONFIG.STATUS_CODE_OK = 200;
CONFIG.STATUS_CODE_SESSION_EXP = 440;
CONFIG.STATUS_CODE_UNAUTHORIZED = 401;
CONFIG.STATUS_CODE_API_NOT_FOUND = 414;
CONFIG.STATUS_CODE_NOT_FOUND = 404;
CONFIG.STATUS_CODE_FOUND = 302;
CONFIG.STATUS_CODE_BAD_REQUEST = 400;
CONFIG.STATUS_CODE_INTERNAL_SERVER = 500;
CONFIG.ERROR_CODE = 422;


// USER STATUS 

CONFIG.UNVERIFIED = 0;
CONFIG.VERIFIED = 1;


CONFIG.INACTIVE_RECORD = 0;
CONFIG.ACTIVE_RECORD = 1;


// missing messages 

CONFIG.ERR_INTERNAL_SERVER_ERROR = 'Internal server error'
CONFIG.ERROR_MISSING_FIRST_NAME = 'Please provide firstName';
CONFIG.ERROR_MISSING_LAST_NAME = 'Please provide lastName';
CONFIG.ERROR_MISSING_GUEST_ID = 'Please provide guest Id';
CONFIG.ERROR_MISSING_USER_ID = 'Please provide user Id';
CONFIG.ERROR_MISSING_VARIANT_ID = 'Please provide variant Id';
CONFIG.ERROR_MISSING_QTY = 'Please provide quantity';
CONFIG.ERROR_MISSING_PHONE = 'Please provide phoneNo';
CONFIG.ERROR_MISSING_ID = 'Please provide ID';
CONFIG.ERROR_MISSING_EMAIL = 'Please provide email';
CONFIG.ERROR_MISSING_PASSWORD = 'Please provide password';
CONFIG.ERROR_MISSING_OTP = 'Please provide otp';
CONFIG.ERROR_MISSING_VERIFY_TYPE = 'Please provide verify type';
CONFIG.ERROR_MISSING_NAME = 'Please provide name';
CONFIG.ERROR_MISSING_PRODUCT_NAME = 'Please provide product name';
CONFIG.ERROR_MISSING_PRODUCT_ID = 'Please provide product id';
CONFIG.ERROR_MISSING_VARIANT_NAME = 'Please provide variant name';
CONFIG.ERROR_MISSING_COLOR = 'Please provide color';
CONFIG.ERROR_MISSING_SIZE = 'Please provide size';
CONFIG.ERROR_MISSING_PRICE = 'Please provide price';
CONFIG.ERROR_MISSING_STOCK = 'Please provide stock';
CONFIG.ERROR_MISSING_MAIN_IMAGE = 'Please provide main image';
CONFIG.ERROR_MISSING_MRP = 'Please provide mrp';
CONFIG.ERROR_MISSING_PRODUCT_HIGHLIGHTS = 'Please provide product highlights';
CONFIG.ERROR_MISSING_PRODUCT_DESCRIPTION = 'Please provide product description';
CONFIG.ERROR_MISSING_OTHER_DESCRIPTION = 'Please provide other description';
CONFIG.ERROR_MISSING_PRODUCT_TYPE = 'Please provide product type';
CONFIG.ERROR_MISSING_PRODUCT_TYPE_ID = 'Please provide product type id';
CONFIG.ERROR_MISSING_PRODUCT_CATEGORY = 'Please provide product category';
CONFIG.ERROR_MISSING_PRODUCT_CATEGORY_ID = 'Please provide product category id';
CONFIG.ERROR_MISSING_PRODUCT_SUBCATEGORY = 'Please provide product subcategory';
CONFIG.ERROR_MISSING_PRODUCT_SUBCATEGORY_ID = 'Please provide product subcategory id';
CONFIG.ERROR_MISSING_AREA_PINCODE = 'Please provide area pincode';
CONFIG.ERROR_MISSING_ADDRESS_LINE_2 = 'Please provide village/town';
CONFIG.ERROR_MISSING_ADDRESS_LINE_1 = 'Please provide address';
CONFIG.ERROR_MISSING_CITY = 'Please provide city';
CONFIG.ERROR_MISSING_STATE = 'Please provide state';


// user types 

CONFIG.USER_TYPE_USER = 1;
CONFIG.USER_TYP_ADMIN = 2;


//Order

CONFIG.ORDER_PAYMENT_PAID = 1;
CONFIG.ORDER_PAYMENT_UNPAID = 0;

CONFIG.ORDER_STATUS_PENDING = 0;
CONFIG.ORDER_STATUS_ORDERD = 1;
CONFIG.ORDER_STATUS_DESPATCHED = 2;
CONFIG.ORDER_STATUS_DELIVERED = 3;


CONFIG.MESS_INTERNAL_SERVER_ERROR = 'Internal server error !'