CONFIG = {};

//API STATUS
CONFIG.STATUS_CODE_OK = 200;
CONFIG.STATUS_CODE_SESSION_EXP = 440;
CONFIG.STATUS_CODE_UNAUTHORIZED = 401;
CONFIG.STATUS_CODE_API_NOT_FOUND = 414;
CONFIG.STATUS_CODE_NOT_FOUND = 404;
CONFIG.STATUS_CODE_FOUND = 302;
CONFIG.STATUS_CODE_BAD_REQUEST = 400;
CONFIG.STATUS_CODE_INTERNAL_SERVER = 500;
CONFIG.ERROR_CODE = 422;